Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -2,48 +2,34 @@ version: 0.2
 
 env:
   variables:
-    S3_BUCKET_NAME: "maheshs3-s3"   # Replace with your actual S3 bucket name
+    S3_BUCKET_NAME: "maheshs3-s3"
 
 phases:
-  install:
-    runtime-versions:
-      nodejs: 18
+  pre_build:
     commands:
-      - echo Pinning npm version
-      - npm install -g npm@8.19.3
-      - echo Installing dependencies
-      - npm ci --retry 3 || npm install
-
-pre_build:
-  commands:
-    - echo "🔍 Checking repo checkpoint..."
-    - |
-      if [ -f checkpoint.json ]; then
-        if grep -q '"deploy": true' checkpoint.json; then
-          echo "✅ Checkpoint passed, continuing pipeline"
+      - echo "🔍 Checking repo checkpoint..."
+      - |
+        if [ -f checkpoint.json ]; then
+          if grep -q '"dev": true' checkpoint.json; then
+            echo "✅ Checkpoint passed, continuing pipeline"
+          else
+            echo "❌ Checkpoint failed, stopping pipeline"
+            exit 1
+          fi
         else
-          echo "❌ Checkpoint failed, stopping pipeline"
+          echo "❌ No checkpoint.json file found, stopping pipeline"
           exit 1
         fi
-      else
-        echo "❌ No checkpoint.json file found, stopping pipeline"
-        exit 1
-      fi
-    - echo Running tests and generating coverage...
-    - CI=true npm test -- --watchAll=false --passWithNoTests
-
 
   build:
     commands:
-      - echo Building React App...
-      - npm run build
+      - echo "📦 No build step needed for static site"
 
   post_build:
     commands:
-      - echo Deploying to S3...
-      - aws s3 sync build/ s3://$S3_BUCKET_NAME/ --delete
+      - echo "🚀 Deploying static site to S3..."
+      - aws s3 sync . s3://$S3_BUCKET_NAME/ --delete --exclude "checkpoint.json" --exclude "buildspec.yml"
 
 artifacts:
-  base-directory: build
   files:
     - '**/*'
